const brewerySiteInspection = {
  screens: [
    {
      name: "General Information",
      sequence: 1,
      sections: [
        {
          name: "Basic Details",
          sequence: 1,
          fields: [
            {
              label: "Brewery Site Inspection Name",
              type: "text",
              sequence: 1,
            },
            {
              label: "Company",
              type: "reference",
              sequence: 2,
              relationshipName: "CompanyId",
            },
            {
              label: "Completed By",
              type: "reference",
              sequence: 3,
              relationshipName: "CompletedBy",
            },
            {
              label: "Conferred With",
              type: "textarea",
              sequence: 4,
            },
            {
              label: "Date of Assessment",
              type: "date",
              sequence: 5,
            },
            {
              label: "Date of Inspection",
              type: "date",
              sequence: 6,
            },
            {
              label: "Reviewed by Name",
              type: "string",
              sequence: 7,
            },
            {
              label: "Reviewed By",
              type: "reference",
              sequence: 8,
              relationshipName: "ReviewedBy",
            },
            {
              label: "Full Address",
              type: "string",
              sequence: 9,
            },
            {
              label: "Location",
              type: "reference",
              sequence: 10,
              relationshipName: "Location",
            },
            {
              label: "File Name",
              type: "string",
              sequence: 11,
            },
            {
              label: "Report Due Date",
              type: "date",
              sequence: 12,
            },
            {
              label: "Status",
              type: "picklist",
              sequence: 13,
              picklistValues: [
                { label: "New", value: "New" },
                { label: "Draft", value: "Draft" },
                { label: "Ready for Review", value: "Ready for Review" },
                { label: "Review Completed", value: "Review Completed" },
                { label: "Report Issued", value: "Report Issued" },
              ],
            },
          ],
        },
        {
          name: "Brewery Safety Checks",
          sequence: 2,
          fields: [
            {
              label: "Adequate lighting in the Brewery?",
              type: "picklist",
              sequence: 14,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Adequate ventilation in the Brewery?",
              type: "picklist",
              sequence: 15,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "All fire extinguisher mounted, accessibl",
              type: "picklist",
              sequence: 16,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Any mechanical aids available to assist",
              type: "picklist",
              sequence: 17,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Appropriate bunding in-place to ensure t",
              type: "picklist",
              sequence: 18,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are Oxygen tanks safely secured and stor",
              type: "picklist",
              sequence: 19,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are Safety Data Sheets (SDSs) accessible",
              type: "picklist",
              sequence: 20,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Area drains covered to prevent pollution",
              type: "picklist",
              sequence: 21,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are all canned goods and pallets secured",
              type: "picklist",
              sequence: 22,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are all confined spaces identified and s",
              type: "picklist",
              sequence: 23,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are all conveyor belts on the bottling/c",
              type: "picklist",
              sequence: 24,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are all guards and safety features prese",
              type: "picklist",
              sequence: 25,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are chillers guarded with appropriate si",
              type: "picklist",
              sequence: 26,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are chillers serviced appropriately?",
              type: "picklist",
              sequence: 27,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are forklift loads secured appropriately",
              type: "picklist",
              sequence: 28,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are forklift operators wearing the seatb",
              type: "picklist",
              sequence: 29,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are hot surfaces communicated via visual",
              type: "picklist",
              sequence: 30,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are pallet jacks in good condition with",
              type: "picklist",
              sequence: 31,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are security controls sufficient to prev",
              type: "picklist",
              sequence: 32,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are the Hazardous Substances stored appr",
              type: "picklist",
              sequence: 33,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are there any traffic control plans avai",
              type: "picklist",
              sequence: 34,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are there available risk assessments det",
              type: "picklist",
              sequence: 35,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are there balers / compactors to assist",
              type: "picklist",
              sequence: 36,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Are wet floor signs available?",
              type: "picklist",
              sequence: 37,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "A risk assessment has been conducted on",
              type: "picklist",
              sequence: 38,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Block plans or evacuation plan displayed",
              type: "picklist",
              sequence: 39,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Blower fans are properly guarded?",
              type: "picklist",
              sequence: 40,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Brewer cannot be splashed with hot liqui",
              type: "picklist",
              sequence: 41,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Brewery hoses used for transfer do not c",
              type: "picklist",
              sequence: 42,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Carbon dioxide storage is secure, levels",
              type: "picklist",
              sequence: 43,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Changes in ground level are highlighted?",
              type: "picklist",
              sequence: 44,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Do all forklifts have up to date logbook",
              type: "picklist",
              sequence: 45,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Do safety in design principles appear to",
              type: "picklist",
              sequence: 46,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Electrical wiring properly insulated and",
              type: "picklist",
              sequence: 47,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Emergency lighting working?",
              type: "picklist",
              sequence: 48,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Exit signs working?",
              type: "picklist",
              sequence: 49,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Glycol fittings are drip free and can be",
              type: "picklist",
              sequence: 50,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Handrails on stairs and platforms are so",
              type: "picklist",
              sequence: 51,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Has a risk assessment been conducted on",
              type: "picklist",
              sequence: 52,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Has a risk assessment been conducted on",
              type: "picklist",
              sequence: 53,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Has a risk assessment been conducted on",
              type: "picklist",
              sequence: 54,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Has a risk assessment been conducted on",
              type: "picklist",
              sequence: 55,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Has a risk assessment been conducted on",
              type: "picklist",
              sequence: 56,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Have electrical devices been tested and",
              type: "picklist",
              sequence: 57,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Have hazards associated with deliveries",
              type: "picklist",
              sequence: 58,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Have plant and equipment that are requir",
              type: "picklist",
              sequence: 59,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Have risk assessments and safe operation",
              type: "picklist",
              sequence: 60,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Hose Reels accessible?",
              type: "picklist",
              sequence: 61,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "If dust is released, is there an appropr",
              type: "picklist",
              sequence: 62,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "If relevant, is there an asbestos regist",
              type: "picklist",
              sequence: 63,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is required PPE used relevant to the typ",
              type: "picklist",
              sequence: 64,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is the charging area for the forklift ke",
              type: "picklist",
              sequence: 65,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is the forklift driver competent and qua",
              type: "picklist",
              sequence: 66,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is the location of compressed air suffic",
              type: "picklist",
              sequence: 67,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is the manual handling of malt likely to",
              type: "picklist",
              sequence: 68,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there a CO2 monitor near the location",
              type: "picklist",
              sequence: 69,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there access to an eyewash and shower",
              type: "picklist",
              sequence: 70,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there a clear, accessible inspection",
              type: "picklist",
              sequence: 71,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there a designated area for trucks an",
              type: "picklist",
              sequence: 72,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there an operating bell for cool room",
              type: "picklist",
              sequence: 73,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there evidence of safe isolation meth",
              type: "picklist",
              sequence: 74,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there evidence that a permit system i",
              type: "picklist",
              sequence: 75,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there evidence that operators are com",
              type: "picklist",
              sequence: 76,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there line markings, signage and othe",
              type: "picklist",
              sequence: 77,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there sufficient space around the mil",
              type: "picklist",
              sequence: 78,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Is there sufficient storage allocated to",
              type: "picklist",
              sequence: 79,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Man cages/work boxes used on forklifts a",
              type: "picklist",
              sequence: 80,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Manual handling of kegs does not cause i",
              type: "picklist",
              sequence: 81,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Paddles are in-built in the mash tun not",
              type: "picklist",
              sequence: 82,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Paths of Egress and access clear?",
              type: "picklist",
              sequence: 83,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "The canning/bottling line is fixed and d",
              type: "picklist",
              sequence: 84,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "The cool room panels (consisting of EPS",
              type: "picklist",
              sequence: 85,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "The height of the stacked pallet no more",
              type: "picklist",
              sequence: 86,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "The process of milling does not create a",
              type: "picklist",
              sequence: 87,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "The top of the mill is not at an adequat",
              type: "picklist",
              sequence: 88,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
            {
              label: "Waterproofing where required?",
              type: "picklist",
              sequence: 89,
              picklistValues: [
                { label: "Partially Adequate", value: "Partially Adequate" },
                { label: "Adequate", value: "Adequate" },
                { label: "Inadequate", value: "Inadequate" },
                { label: "N/A", value: "N/A" },
              ],
            },
          ],
        },
        {
          name: "Comments Section",
          sequence: 3,
          fields: [
            {
              label: "Comments",
              type: "textarea",
              sequence: 90,
              name: "Commentsboiling",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 91,
              name: "Commentsconfinedspaces",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 92,
              name: "Commentscooling",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 93,
              name: "Commentsdeliveryofmaterial",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 94,
              name: "Commentsemergency",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 95,
              name: "Commentsfermentation",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 96,
              name: "Commentshazardous",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 97,
              name: "Commentsheat",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 98,
              name: "Commentshousekeeping",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 99,
              name: "Commentskegging",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 100,
              name: "Commentsmachinery",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 101,
              name: "Commentsmashing",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 102,
              name: "Commentsmaturing",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 103,
              name: "Commentsmilling",
            },
            {
              label: "Comments",
              type: "textarea",
              sequence: 104,
              name: "Commentsrefrigerated",
            },
          ],
        },
      ],
    },
  ],
};

module.exports = brewerySiteInspection;