const hazardInspection = {
  screens: [
    {
      name: "General Information",
      sequence: 1,
      sections: [
        {
          name: "Basic Details",
          sequence: 1,
          fields: [
            {
              label: "Hazard Inspection Name",
              type: "string",
              sequence: 1,
            },
            {
              label: "Company",
              type: "reference",
              sequence: 2,
              relationshipName: "CompanyId",
            },
            {
              label: "Company Location",
              type: "reference",
              sequence: 3,
              relationshipName: "CompanyLocationId",
            },
            {
              label: "Assigned To",
              type: "reference",
              sequence: 4,
              relationshipName: "CompletedBy",
            },
            {
              label: "Conferred With",
              type: "textarea",
              sequence: 5,
            },
            {
              label: "Date of Assessment",
              type: "date",
              sequence: 6,
            },
            {
              label: "Account Manager",
              type: "string",
              sequence: 7,
            },
            {
              label: "Reviewed By",
              type: "reference",
              sequence: 8,
              relationshipName: "ReviewedBy",
            },
            {
              label: "Full Address",
              type: "string",
              sequence: 9,
            },
            {
              label: "File Name",
              type: "string",
              sequence: 10,
            },
            {
              label: "Property Risk Assessment",
              type: "reference",
              sequence: 11,
              relationshipName: "PropertyRiskAssessmentID",
            },
            {
              label: "Target Goods",
              type: "string",
              sequence: 12,
            },
            {
              label: "Maximum Amount of Cash Held",
              type: "string",
              sequence: 13,
            },
            {
              label: "Frequency of Patrols",
              type: "string",
              sequence: 14,
            },
            {
              label: "Report Due Date",
              type: "date",
              sequence: 15,
            },
            {
              label: "Reviewer Comment",
              type: "textarea",
              sequence: 16,
            },
            {
              label: "Status",
              type: "picklist",
              sequence: 17,
              picklistValues: [],
            },
            {
              label: "Total Questions",
              type: "double",
              sequence: 18,
            },
            {
              label: "Total Answered",
              type: "double",
              sequence: 19,
            },
          ],
        },
        {
          name: "Hazard Identification",
          sequence: 2,
          fields: [
            {
              label: "Accessible Windows Fitted with Locks",
              type: "picklist",
              sequence: 20,
              picklistValues: [],
            },
            {
              label: "Adequate bunding and spill kits for any",
              type: "picklist",
              sequence: 21,
              picklistValues: [],
            },
            {
              label: "Alarm Connection",
              type: "picklist",
              sequence: 22,
              picklistValues: [],
            },
            {
              label: "Alarm Type",
              type: "picklist",
              sequence: 23,
              picklistValues: [],
            },
            {
              label: "All fire extinguisher mounted, accessibl",
              type: "picklist",
              sequence: 24,
              picklistValues: [],
            },
            {
              label: "All staff in the loading zone wearing hi",
              type: "picklist",
              sequence: 25,
              picklistValues: [],
            },
            {
              label: "Any permits issued to contractors for hi",
              type: "picklist",
              sequence: 26,
              picklistValues: [],
            },
            {
              label: "Any points of release in the process?",
              type: "picklist",
              sequence: 27,
              picklistValues: [],
            },
            {
              label: "Any processes on-site that produce combu",
              type: "picklist",
              sequence: 28,
              picklistValues: [],
            },
            {
              label: "Appropriate equipment used for handling",
              type: "picklist",
              sequence: 29,
              picklistValues: [],
            },
            {
              label: "Approval",
              type: "picklist",
              sequence: 30,
              picklistValues: [],
            },
            {
              label: "Are Electrical Switch-rooms kept free of",
              type: "picklist",
              sequence: 31,
              picklistValues: [],
            },
            {
              label: "Are Electrical Switch-rooms lockable and",
              type: "picklist",
              sequence: 32,
              picklistValues: [],
            },
            {
              label: "Are Electrical cabinets with live connec",
              type: "picklist",
              sequence: 33,
              picklistValues: [],
            },
            {
              label: "Are Site Managers aware of Contractor pr",
              type: "picklist",
              sequence: 34,
              picklistValues: [],
            },
            {
              label: "Are all forklift driver licensed?",
              type: "picklist",
              sequence: 35,
              picklistValues: [],
            },
            {
              label: "Are all guards and safety features prese",
              type: "picklist",
              sequence: 36,
              picklistValues: [],
            },
            {
              label: "Areas Protected",
              type: "picklist",
              sequence: 37,
              picklistValues: [],
            },
            {
              label: "Are asset protected from damage of forkl",
              type: "picklist",
              sequence: 38,
              picklistValues: [],
            },
            {
              label: "Are contractors monitored on site or do",
              type: "picklist",
              sequence: 39,
              picklistValues: [],
            },
            {
              label: "Are electrical leads tagged (6 monthly)",
              type: "picklist",
              sequence: 40,
              picklistValues: [],
            },
            {
              label: "Are emergency numbers displayed?",
              type: "picklist",
              sequence: 41,
              picklistValues: [],
            },
            {
              label: "Are first aid officers accessible (if re",
              type: "picklist",
              sequence: 42,
              picklistValues: [],
            },
            {
              label: "Are forklifts checked for safety before",
              type: "picklist",
              sequence: 43,
              picklistValues: [],
            },
            {
              label: "Are gas bottles secured? (If onsite)",
              type: "picklist",
              sequence: 44,
              picklistValues: [],
            },
            {
              label: "Are guardrails provided at all working p",
              type: "picklist",
              sequence: 45,
              picklistValues: [],
            },
            {
              label: "Are incidents on the asset reported, rec",
              type: "picklist",
              sequence: 46,
              picklistValues: [],
            },
            {
              label: "Are insurances and licences checked prio",
              type: "picklist",
              sequence: 47,
              picklistValues: [],
            },
            {
              label: "Are ladders in good condition?",
              type: "picklist",
              sequence: 48,
              picklistValues: [],
            },
            {
              label: "Are liquid spills removed quickly?",
              type: "picklist",
              sequence: 49,
              picklistValues: [],
            },
            {
              label: "Are products being unloaded/loaded onto",
              type: "picklist",
              sequence: 50,
              picklistValues: [],
            },
            {
              label: "Are products store safely with no potent",
              type: "picklist",
              sequence: 51,
              picklistValues: [],
            },
            {
              label: "Are solid construction platforms in good",
              type: "picklist",
              sequence: 52,
              picklistValues: [],
            },
            {
              label: "Are stop switches and Isolation points c",
              type: "picklist",
              sequence: 53,
              picklistValues: [],
            },
            {
              label: "Are there any hazardous substances or da",
              type: "picklist",
              sequence: 54,
              picklistValues: [],
            },
            {
              label: "Are there processes in place for COR obl",
              type: "picklist",
              sequence: 55,
              picklistValues: [],
            },
            {
              label: "Are volumes and storage conditions in ac",
              type: "picklist",
              sequence: 56,
              picklistValues: [],
            },
            {
              label: "Block plans or evacuation plan displayed",
              type: "picklist",
              sequence: 57,
              picklistValues: [],
            },
            {
              label: "Carpet",
              type: "picklist",
              sequence: 58,
              picklistValues: [],
            },
            {
              label: "Chain of Responsibility",
              type: "picklist",
              sequence: 59,
              picklistValues: [],
            },
            {
              label: "Chemical Storage and Handling",
              type: "picklist",
              sequence: 60,
              picklistValues: [],
            },
            {
              label: "Chemicals are also stored to ensure ther",
              type: "picklist",
              sequence: 61,
              picklistValues: [],
            },
            {
              label: "Clear separation between the loading/unl",
              type: "picklist",
              sequence: 62,
              picklistValues: [],
            },
            {
              label: "Combustible Dust",
              type: "picklist",
              sequence: 63,
              picklistValues: [],
            },
            {
              label: "Confined Spaces",
              type: "picklist",
              sequence: 64,
              picklistValues: [],
            },
            {
              label: "Contract Register",
              type: "picklist",
              sequence: 65,
              picklistValues: [],
            },
            {
              label: "Contractors are used on site go through",
              type: "picklist",
              sequence: 66,
              picklistValues: [],
            },
            {
              label: "Contractual Lease Agreements",
              type: "picklist",
              sequence: 67,
              picklistValues: [],
            },
            {
              label: "Correct labelling of containers and pipe",
              type: "picklist",
              sequence: 68,
              picklistValues: [],
            },
            {
              label: "Defibrillator Available and Accessible?",
              type: "picklist",
              sequence: 69,
              picklistValues: [],
            },
            {
              label: "Do activities on site during inspection",
              type: "picklist",
              sequence: 70,
              picklistValues: [],
            },
            {
              label: "Do contractors conduct high-risk works?",
              type: "picklist",
              sequence: 71,
              picklistValues: [],
            },
            {
              label: "Do contractors provide SWMS for the work",
              type: "picklist",
              sequence: 72,
              picklistValues: [],
            },
            {
              label: "Does the facility have a loading dock?",
              type: "picklist",
              sequence: 73,
              picklistValues: [],
            },
            {
              label: "Doors and Windows Alarmed",
              type: "picklist",
              sequence: 74,
              picklistValues: [],
            },
            {
              label: "Do safety in design principles appear to",
              type: "picklist",
              sequence: 75,
              picklistValues: [],
            },
            {
              label: "Dust collector available?",
              type: "picklist",
              sequence: 76,
              picklistValues: [],
            },
            {
              label: "Dust collector has explosion venting out",
              type: "picklist",
              sequence: 77,
              picklistValues: [],
            },
            {
              label: "Electrical Safety",
              type: "picklist",
              sequence: 78,
              picklistValues: [],
            },
            {
              label: "Electrical Security",
              type: "picklist",
              sequence: 79,
              picklistValues: [],
            },
            {
              label: "Electronic Intruder Alarm System",
              type: "picklist",
              sequence: 80,
              picklistValues: [],
            },
            {
              label: "Electronic Security",
              type: "picklist",
              sequence: 81,
              picklistValues: [],
            },
            {
              label: "Elevated Work Platform in good condition",
              type: "picklist",
              sequence: 82,
              picklistValues: [],
            },
            {
              label: "Emergency Response",
              type: "picklist",
              sequence: 83,
              picklistValues: [],
            },
            {
              label: "Emergency lighting working?",
              type: "picklist",
              sequence: 84,
              picklistValues: [],
            },
            {
              label: "Employed or Contracted",
              type: "picklist",
              sequence: 85,
              picklistValues: [],
            },
            {
              label: "Employees aware of location of first aid",
              type: "picklist",
              sequence: 86,
              picklistValues: [],
            },
            {
              label: "Entry and walkways kept clear?",
              type: "picklist",
              sequence: 87,
              picklistValues: [],
            },
            {
              label: "Equipment cleaned and stored away in cor",
              type: "picklist",
              sequence: 88,
              picklistValues: [],
            },
            {
              label: "Evacuation procedures and emergency prep",
              type: "picklist",
              sequence: 89,
              picklistValues: [],
            },
            {
              label: "Event risk assessment been conducted?",
              type: "picklist",
              sequence: 90,
              picklistValues: [],
            },
            {
              label: "Events",
              type: "picklist",
              sequence: 91,
              picklistValues: [],
            },
            {
              label: "Evidence of corrective action monitoring",
              type: "picklist",
              sequence: 92,
              picklistValues: [],
            },
            {
              label: "Exit signs working?",
              type: "picklist",
              sequence: 93,
              picklistValues: [],
            },
            {
              label: "Exposure to Sudden and Unforeseen Pollut",
              type: "picklist",
              sequence: 94,
              picklistValues: [],
            },
            {
              label: "External/Internal",
              type: "picklist",
              sequence: 95,
              picklistValues: [],
            },
            {
              label: "Fire Prevention",
              type: "picklist",
              sequence: 96,
              picklistValues: [],
            },
            {
              label: "Fire Wardens have been trained on-site?",
              type: "picklist",
              sequence: 97,
              picklistValues: [],
            },
            {
              label: "Fire hydrants are operational",
              type: "picklist",
              sequence: 98,
              picklistValues: [],
            },
            {
              label: "Fire sprinklers are operational?",
              type: "picklist",
              sequence: 99,
              picklistValues: [],
            },
            {
              label: "First Aid Requirements",
              type: "picklist",
              sequence: 100,
              picklistValues: [],
            },
            {
              label: "First Aid kits installed and accessible?",
              type: "picklist",
              sequence: 101,
              picklistValues: [],
            },
            {
              label: "First aid requirements displayed?",
              type: "picklist",
              sequence: 102,
              picklistValues: [],
            },
            {
              label: "Flammable Liquids",
              type: "picklist",
              sequence: 103,
              picklistValues: [],
            },
            {
              label: "Floorboards",
              type: "picklist",
              sequence: 104,
              picklistValues: [],
            },
            {
              label: "Floor mats used to avoid slip trips and",
              type: "picklist",
              sequence: 105,
              picklistValues: [],
            },
            {
              label: "Floor surfaces clean and uncluttered?",
              type: "picklist",
              sequence: 106,
              picklistValues: [],
            },
            {
              label: "Food Safety",
              type: "picklist",
              sequence: 107,
              picklistValues: [],
            },
            {
              label: "Forklift",
              type: "picklist",
              sequence: 108,
              picklistValues: [],
            },
            {
              label: "Forklifts have automatic flashing lights",
              type: "picklist",
              sequence: 109,
              picklistValues: [],
            },
            {
              label: "Forklifts have seat belts and are they b",
              type: "picklist",
              sequence: 110,
              picklistValues: [],
            },
            {
              label: "General Public access has been limited?",
              type: "picklist",
              sequence: 111,
              picklistValues: [],
            },
            {
              label: "General Safety",
              type: "picklist",
              sequence: 112,
              picklistValues: [],
            },
            {
              label: "Has a manual handling risk assessment be",
              type: "picklist",
              sequence: 113,
              picklistValues: [],
            },
            {
              label: "Has a thermographic scans conducted on e",
              type: "picklist",
              sequence: 114,
              picklistValues: [],
            },
            {
              label: "Has confined space been identified on-si",
              type: "picklist",
              sequence: 115,
              picklistValues: [],
            },
            {
              label: "Has the AFSS (or equivalant) been comple",
              type: "picklist",
              sequence: 116,
              picklistValues: [],
            },
            {
              label: "Have WHS Performance Metrics and initiat",
              type: "picklist",
              sequence: 117,
              picklistValues: [],
            },
            {
              label: "Have high-risk areas for Falls been iden",
              type: "picklist",
              sequence: 118,
              picklistValues: [],
            },
            {
              label: "Have plant and equipment that are requir",
              type: "picklist",
              sequence: 119,
              picklistValues: [],
            },
            {
              label: "Have staff been trained in Manual Handli",
              type: "picklist",
              sequence: 120,
              picklistValues: [],
            },
            {
              label: "Hazard inspection has been conducted?",
              type: "picklist",
              sequence: 121,
              picklistValues: [],
            },
            {
              label: "Hazardous Area Zoning in place and under",
              type: "picklist",
              sequence: 122,
              picklistValues: [],
            },
            {
              label: "Hazardous Area Zoning in place and under",
              type: "picklist",
              sequence: 123,
              picklistValues: [],
            },
            {
              label: "Hazardous Substances",
              type: "picklist",
              sequence: 124,
              picklistValues: [],
            },
            {
              label: "Hazards Identified",
              type: "picklist",
              sequence: 125,
              picklistValues: [],
            },
            {
              label: "Hose Reels accessible?",
              type: "picklist",
              sequence: 126,
              picklistValues: [],
            },
            {
              label: "Hot Work",
              type: "picklist",
              sequence: 127,
              picklistValues: [],
            },
            {
              label: "Housekeeping regime available to minimis",
              type: "picklist",
              sequence: 128,
              picklistValues: [],
            },
            {
              label: "Incident Management",
              type: "picklist",
              sequence: 129,
              picklistValues: [],
            },
            {
              label: "Induction",
              type: "picklist",
              sequence: 130,
              picklistValues: [],
            },
            {
              label: "Interaction with General Public?",
              type: "picklist",
              sequence: 131,
              picklistValues: [],
            },
            {
              label: "Intersections kept clear of boxes or mat",
              type: "picklist",
              sequence: 132,
              picklistValues: [],
            },
            {
              label: "Is access to fall risk areas controlled",
              type: "picklist",
              sequence: 133,
              picklistValues: [],
            },
            {
              label: "Is access to forklifts controlled to app",
              type: "picklist",
              sequence: 134,
              picklistValues: [],
            },
            {
              label: "Is an updated Asset Management plan read",
              type: "picklist",
              sequence: 135,
              picklistValues: [],
            },
            {
              label: "Is flammable liquid stored and used on s",
              type: "picklist",
              sequence: 136,
              picklistValues: [],
            },
            {
              label: "Is hot work conducted in an isolated or",
              type: "picklist",
              sequence: 137,
              picklistValues: [],
            },
            {
              label: "Is required PPE used relevant to the typ",
              type: "picklist",
              sequence: 138,
              picklistValues: [],
            },
            {
              label: "Is the circuit protection on switchboard",
              type: "picklist",
              sequence: 139,
              picklistValues: [],
            },
            {
              label: "Is the manual handling of any products b",
              type: "picklist",
              sequence: 140,
              picklistValues: [],
            },
            {
              label: "Is there a WHS policy available?",
              type: "picklist",
              sequence: 141,
              picklistValues: [],
            },
            {
              label: "Is there a chemical register or manifest",
              type: "picklist",
              sequence: 142,
              picklistValues: [],
            },
            {
              label: "Is there a clear, accessible inspection",
              type: "picklist",
              sequence: 143,
              picklistValues: [],
            },
            {
              label: "Is there a confined space permit?",
              type: "picklist",
              sequence: 144,
              picklistValues: [],
            },
            {
              label: "Is there a confined space register?",
              type: "picklist",
              sequence: 145,
              picklistValues: [],
            },
            {
              label: "Is there adequate storage of chemicals i",
              type: "picklist",
              sequence: 146,
              picklistValues: [],
            },
            {
              label: "Is there a fire watch required for all h",
              type: "picklist",
              sequence: 147,
              picklistValues: [],
            },
            {
              label: "Is there a hot work permit and is there",
              type: "picklist",
              sequence: 148,
              picklistValues: [],
            },
            {
              label: "Is there an electrical isolation system",
              type: "picklist",
              sequence: 149,
              picklistValues: [],
            },
            {
              label: "Is there appropriate lifting equipment t",
              type: "picklist",
              sequence: 150,
              picklistValues: [],
            },
            {
              label: "Is there a process to on-board/induct co",
              type: "picklist",
              sequence: 151,
              picklistValues: [],
            },
            {
              label: "Is there evidence of relevant issues, ha",
              type: "picklist",
              sequence: 152,
              picklistValues: [],
            },
            {
              label: "Is there evidence that emergency drills",
              type: "picklist",
              sequence: 153,
              picklistValues: [],
            },
            {
              label: "Is there evidence that operators are com",
              type: "picklist",
              sequence: 154,
              picklistValues: [],
            },
            {
              label: "Is the risk register up to date for the",
              type: "picklist",
              sequence: 155,
              picklistValues: [],
            },
            {
              label: "Is the work area required to be monitore",
              type: "picklist",
              sequence: 156,
              picklistValues: [],
            },
            {
              label: "Kits full of contents?",
              type: "picklist",
              sequence: 157,
              picklistValues: [],
            },
            {
              label: "Loading and Unloading Area",
              type: "picklist",
              sequence: 158,
              picklistValues: [],
            },
            {
              label: "Loading area clean and tidy?",
              type: "picklist",
              sequence: 159,
              picklistValues: [],
            },
            {
              label: "Locking Devices",
              type: "picklist",
              sequence: 160,
              picklistValues: [],
            },
            {
              label: "Machinery Safety",
              type: "picklist",
              sequence: 161,
              picklistValues: [],
            },
            {
              label: "Manual Tasks or Processes",
              type: "picklist",
              sequence: 162,
              picklistValues: [],
            },
            {
              label: "Monitor",
              type: "picklist",
              sequence: 163,
              picklistValues: [],
            },
            {
              label: "Movement Detectors Provided",
              type: "picklist",
              sequence: 164,
              picklistValues: [],
            },
            {
              label: "No broken plugs, sockets or switches?",
              type: "picklist",
              sequence: 165,
              picklistValues: [],
            },
            {
              label: "No contents past their expiry date?",
              type: "picklist",
              sequence: 166,
              picklistValues: [],
            },
            {
              label: "No frayed or damaged leads?",
              type: "picklist",
              sequence: 167,
              picklistValues: [],
            },
            {
              label: "No power leads across walkways?",
              type: "picklist",
              sequence: 168,
              picklistValues: [],
            },
            {
              label: "On-site",
              type: "picklist",
              sequence: 169,
              picklistValues: [],
            },
            {
              label: "Operators trained/inducted into the oper",
              type: "picklist",
              sequence: 170,
              picklistValues: [],
            },
            {
              label: "Paths of Egress and access clear?",
              type: "picklist",
              sequence: 171,
              picklistValues: [],
            },
            {
              label: "Pavers",
              type: "picklist",
              sequence: 172,
              picklistValues: [],
            },
            {
              label: "Perimeter Protection",
              type: "picklist",
              sequence: 173,
              picklistValues: [],
            },
            {
              label: "Physical Security",
              type: "picklist",
              sequence: 174,
              picklistValues: [],
            },
            {
              label: "Plant risk assessments have been conduct",
              type: "picklist",
              sequence: 175,
              picklistValues: [],
            },
            {
              label: "Portable electrical equipment in good co",
              type: "picklist",
              sequence: 176,
              picklistValues: [],
            },
            {
              label: "Public Safety",
              type: "picklist",
              sequence: 177,
              picklistValues: [],
            },
            {
              label: "Public and Non-Public Interface Access",
              type: "picklist",
              sequence: 178,
              picklistValues: [],
            },
            {
              label: "Register of Key /Card Issuance",
              type: "picklist",
              sequence: 179,
              picklistValues: [],
            },
            {
              label: "Restricted Profile Security Key",
              type: "picklist",
              sequence: 180,
              picklistValues: [],
            },
            {
              label: "Review and Approval Process",
              type: "picklist",
              sequence: 181,
              picklistValues: [],
            },
            {
              label: "Safe",
              type: "picklist",
              sequence: 182,
              picklistValues: [],
            },
            {
              label: "Sealed Surfaces External",
              type: "picklist",
              sequence: 183,
              picklistValues: [],
            },
            {
              label: "Sealed Surfaces Internal",
              type: "picklist",
              sequence: 184,
              picklistValues: [],
            },
            {
              label: "Security Grills",
              type: "picklist",
              sequence: 185,
              picklistValues: [],
            },
            {
              label: "Security Lighting",
              type: "picklist",
              sequence: 186,
              picklistValues: [],
            },
            {
              label: "Security Patrol Services",
              type: "picklist",
              sequence: 187,
              picklistValues: [],
            },
            {
              label: "Security Patrol",
              type: "picklist",
              sequence: 188,
              picklistValues: [],
            },
            {
              label: "Stair and risers kept clear?",
              type: "picklist",
              sequence: 189,
              picklistValues: [],
            },
            {
              label: "Static earthing in place?",
              type: "picklist",
              sequence: 190,
              picklistValues: [],
            },
            {
              label: "Static earthing in place?",
              type: "picklist",
              sequence: 191,
              picklistValues: [],
            },
            {
              label: "Steps",
              type: "picklist",
              sequence: 192,
              picklistValues: [],
            },
            {
              label: "Storage racks are in good condition?",
              type: "picklist",
              sequence: 193,
              picklistValues: [],
            },
            {
              label: "Storage racks are inspected by certified",
              type: "picklist",
              sequence: 194,
              picklistValues: [],
            },
            {
              label: "Storages are not overloaded with product",
              type: "picklist",
              sequence: 195,
              picklistValues: [],
            },
            {
              label: "Theft Exposure",
              type: "picklist",
              sequence: 196,
              picklistValues: [
                {
                  label: "Yes",
                  value: "Yes",
                },
                {
                  label: "No",
                  value: "No",
                }
              ],
            },
            {
              label: "Third Party Occupants",
              type: "picklist",
              sequence: 197,
              picklistValues: [
                {
                  label: "Yes",
                  value: "Yes",
                },
                {
                  label: "No",
                  value: "No",
                },
              ],
            },
            {
              label: "Traffic Management Plan documented, unde",
              type: "picklist",
              sequence: 198,
              picklistValues: [
                {
                  label: "Yes",
                  value: "Yes",
                },
                {
                  label: "No",
                  value: "No",
                },
              ],
            },
            {
              label: "Trained and certified personnel enter th",
              type: "picklist",
              sequence: 199,
              picklistValues: [],
            },
            {
              label: "Transitions",
              type: "picklist",
              sequence: 200,
              picklistValues: [],
            },
            {
              label: "Work benches clean and clear of rubbish",
              type: "picklist",
              sequence: 201,
              picklistValues: [],
            },
            {
              label: "Working at Heights",
              type: "picklist",
              sequence: 202,
              picklistValues: [],
            },
            {
              label: "Emergency Plan",
              type: "picklist",
              sequence: 203,
              picklistValues: [],
            },
          ],
        },
        {
          name: "Comments Section",
          sequence: 3,
          fields: [
            {
              label: "Comments Approval",
              type: "textarea",
              sequence: 204,
            },
            {
              label: "Comments Chain of Responsibility",
              type: "textarea",
              sequence: 205,
            },
            {
              label: "Comments Combustible Dust",
              type: "textarea",
              sequence: 206,
            },
            {
              label: "Comments Condition of Floors and Surface",
              type: "textarea",
              sequence: 207,
            },
            {
              label: "Comments Confined Spaces",
              type: "textarea",
              sequence: 208,
            },
            {
              label: "Comments Contracts",
              type: "textarea",
              sequence: 209,
            },
            {
              label: "Comments Electrical Safety",
              type: "textarea",
              sequence: 210,
            },
            {
              label: "Comments Electrical Security",
              type: "textarea",
              sequence: 211,
            },
            {
              label: "Comments Emergency Response",
              type: "textarea",
              sequence: 212,
            },
            {
              label: "Comments Environment",
              type: "textarea",
              sequence: 213,
            },
            {
              label: "Comments Fire Prevention",
              type: "textarea",
              sequence: 214,
            },
            {
              label: "Comments First Aid Requirements",
              type: "textarea",
              sequence: 215,
            },
            {
              label: "Comments Flammable Liquids",
              type: "textarea",
              sequence: 216,
            },
            {
              label: "Comments Forklift",
              type: "textarea",
              sequence: 217,
            },
            {
              label: "Comments General Safety",
              type: "textarea",
              sequence: 218,
            },
            {
              label: "Comments General WHS",
              type: "textarea",
              sequence: 219,
            },
            {
              label: "Comments Hazardous Substances",
              type: "textarea",
              sequence: 220,
            },
            {
              label: "Comments Hot Work",
              type: "textarea",
              sequence: 221,
            },
            {
              label: "Comments Housekeeping",
              type: "textarea",
              sequence: 222,
            },
            {
              label: "Comments Incident Management",
              type: "textarea",
              sequence: 223,
            },
            {
              label: "Comments Induction",
              type: "textarea",
              sequence: 224,
            },
            {
              label: "Comments Loading and Unloading Area",
              type: "textarea",
              sequence: 225,
            },
            {
              label: "Comments Machinery Safety",
              type: "textarea",
              sequence: 226,
            },
            {
              label: "Comments Manual Tasks or Processes",
              type: "textarea",
              sequence: 227,
            },
            {
              label: "Comments Monitor",
              type: "textarea",
              sequence: 228,
            },
            {
              label: "Comments Onsite",
              type: "textarea",
              sequence: 229,
            },
            {
              label: "Comments Physical Security",
              type: "textarea",
              sequence: 230,
            },
            {
              label: "Comments Public Safety Hazards",
              type: "textarea",
              sequence: 231,
            },
            {
              label: "Comments Public Safety",
              type: "textarea",
              sequence: 232,
            },
            {
              label: "Comments Risk Control",
              type: "textarea",
              sequence: 233,
            },
            {
              label: "Comments Security Patrol Services",
              type: "textarea",
              sequence: 234,
            },
            {
              label: "Comments Security",
              type: "textarea",
              sequence: 235,
            },
            {
              label: "Comments Theft Exposure",
              type: "textarea",
              sequence: 236,
            },
            {
              label: "Comments Work Health and Safety",
              type: "textarea",
              sequence: 237,
            },
            {
              label: "Comments Working at Heights",
              type: "textarea",
              sequence: 238,
            },
          ],
        },
      ],
    },
  ],
};

module.exports = hazardInspection;
